### PR TITLE
Fixes #281

### LINKED ISSUE #281: TypeError at /cas/login: 'NoneType' object is not subscriptable
**Platform & Version**
Platform: Linux
django-cas-ng: git master (e330c19)
Django: 2.2.19
Python: 3.9.1
CAS Server Software and version: 

**Describe the bug**
TypeError occurs on login, preventing successful login.

**To Reproduce**
I'm able to reproduce the following error in my development environment, when I try to log in with CAS using django_cas_ng.

**Expected behavior**
Successful CAS login

**Screenshots**
Screenshot_2021-03-10_12-40-37
Screenshot_2021-03-10_12-40-14

**Additional context**
At line 143 of views.py, `request.session.session_key` can be `None` in some cases, causing this python error.

### PR DESCRIPTION
**Pull request by davidmgvaz**
session.session_key is None for signed_cookies sessions on first request

### CODE REVIEW

**Comment by nikolas** [comment]
This change fixes a login error that was occurring on my systems. Would be good to review and merge into master. @mingchen

**Comment by mingchen** [comment]
@nikolas Can you check my previous comment ? 
I am not sure what's this change will import line 144. will session always be created before line 144? Is there any negative impact?

**Comment by nikolas** [comment]
After looking at this patch within the surrounding code, I see a minor thing to change here. Currently the procedure is like this:
```
            # from https://code.djangoproject.com/ticket/19147
            if not request.session.session_key:
                request.session.save()

            # Truncate session key to a max of its value length.
            # When using the signed_cookies session backend, the
            # session key can potentially be longer than this.
            session_key = request.session.session_key[:SESSION_KEY_MAXLENGTH]

            if not request.session.exists(session_key):
                request.session.create()
```

While this would be safer, to create `request.session` at the right time if it doesn't exist:
```
            if not request.session.exists(session_key):
                request.session.create()

            # from https://code.djangoproject.com/ticket/19147
            if not request.session.session_key:
                request.session.save()

            # Truncate session key to a max of its value length.
            # When using the signed_cookies session backend, the
            # session key can potentially be longer than this.
            session_key = request.session.session_key[:SESSION_KEY_MAXLENGTH]
```

**Comment by nikolas** [comment]
Session will only be created if necessary, at line 137. I've been using this version in production for a month, and it's working well, so this can be merged as is.

**Comment by mingchen** [comment]
Thanks.

**Pull request merged**
